pagopa/emd-message-core

- openapi.yaml
- src/main/java/it/gov/pagopa/message/core/stub/controller/StubMessageCoreController.java
-Updated servers in openapi.yaml
> fix: Update swagger

- src/main/resources/application.yml
> fix: Time Zone Change

- src/main/java/it/gov/pagopa/message/core/stub/controller/ReactController.java
> fix: Frontend File Position Change

- .github/workflows/code-review.yml
- pom.xml
> fix: add code revieve pipeline

- .devops/code-review-pipelines.yml
- .github/workflows/code-review.yml
- src/main/java/it/gov/pagopa/message/core/controller/CitizenController.java
- src/main/java/it/gov/pagopa/message/core/controller/CitizenControllerImpl.java
- src/main/java/it/gov/pagopa/message/core/service/SendMessageServiceImpl.java
> fix: Code review test

- src/main/java/it/gov/pagopa/message/core/controller/CitizenController.java
- src/main/java/it/gov/pagopa/message/core/controller/CitizenControllerImpl.java
> fix: update delete method

- .github/workflows/code-review.yml
- src/main/java/it/gov/pagopa/message/core/service/SendMessageServiceImpl.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/message/core/controller/CitizenControllerTest.java
> fix: Added TPP secret

- .github/workflows/code-review.yml
- src/main/java/it/gov/pagopa/message/core/dto/CitizenConsentDTO.java
- src/test/java/it/gov/pagopa/common/utils/UtilsTest.java
- src/test/java/it/gov/pagopa/common/web/exception/ValidationExceptionHandlerTest.java
- src/test/java/it/gov/pagopa/message/core/event/producer/MessageErrorProducerTest.java
- src/test/java/it/gov/pagopa/message/core/service/CitizenServiceTest.java
- Test fix for sonar cloud Issues
> fix: Sonar cloud issues fix

- .github/workflows/code-review.yml
- src/main/java/it/gov/pagopa/common/web/exception/ClientExceptionNoBody.java
> fix: Code review update

- src/main/java/it/gov/pagopa/message/core/dto/MessageDTO.java
- src/main/java/it/gov/pagopa/message/core/stub/model/Message.java
- src/test/java/it/gov/pagopa/message/core/controller/MessageCoreControllerTest.java
- src/test/java/it/gov/pagopa/message/core/faker/MessageDTOFaker.java
> fix: Trigger date time type change

- .grype.yaml
- pom.xml
- Update maven dependency to fix CVE
> fix: Update maven dependency to fix cve

- .grype.yaml
- pom.xml
- src/main/java/it/gov/pagopa/common/utils/Utils.java
- src/main/java/it/gov/pagopa/message/core/event/producer/MessageErrorProducer.java
- src/main/java/it/gov/pagopa/message/core/service/ChannelServiceImpl.java
- src/main/java/it/gov/pagopa/message/core/service/CitizenServiceImpl.java
- src/main/java/it/gov/pagopa/message/core/service/MessageCoreServiceImpl.java
- src/main/java/it/gov/pagopa/message/core/service/MessageErrorConsumerServiceImpl.java
- src/main/java/it/gov/pagopa/message/core/service/SendMessageServiceImpl.java
- src/test/java/it/gov/pagopa/message/core/service/SendMessageServiceTest.java
> fix: resolve CVE and log injection

- pom.xml
- src/test/java/it/gov/pagopa/message/controller/MessageCoreControllerTest.java
> fix: pom change

- src/main/resources/application.yml
> fix: feign setting pom update

- src/main/java/it/gov/pagopa/message/connector/citizen/CitizenConnectorImpl.java
- src/main/java/it/gov/pagopa/message/connector/tpp/TppConnectorImpl.java
> fix: web client fix

- src/main/java/it/gov/pagopa/message/connector/citizen/CitizenConnectorImpl.java
- src/main/java/it/gov/pagopa/message/controller/MessageCoreController.java
> fix: api change

- src/main/java/it/gov/pagopa/message/service/MessageCoreServiceImpl.java
> fix: process messages fix

- src/main/java/it/gov/pagopa/message/service/MessageCoreServiceImpl.java
> fix: send messages fix

- src/main/java/it/gov/pagopa/message/service/MessageErrorConsumerServiceImpl.java
> fix: queue consumer fix

- src/main/java/it/gov/pagopa/message/service/MessageErrorConsumerServiceImpl.java
> fix: queue consumer 

- src/main/java/it/gov/pagopa/message/configuration/SchedulerConfiguration.java
> fix: queue scheduling fix

- src/main/java/it/gov/pagopa/message/event/producer/MessageErrorProducer.java
> fix: queue scheduling 

- src/main/java/it/gov/pagopa/message/dto/MessageDTO.java
- MessageDTO class attributes update
> fix: Message model update

- src/main/java/it/gov/pagopa/common/mongo/MongoConfig.java
- src/main/java/it/gov/pagopa/common/mongo/MongoHealthConfig.java
- src/main/java/it/gov/pagopa/common/web/dto/ErrorDTO.java
- src/main/java/it/gov/pagopa/message/dto/MessageDTO.java
- src/main/java/it/gov/pagopa/message/event/producer/MessageProducer.java
- src/main/java/it/gov/pagopa/message/service/MessageProducerServiceImpl.java
- src/test/java/it/gov/pagopa/common/reactive/utils/PerformanceLoggerTest.java
- src/test/java/it/gov/pagopa/common/utils/CommonUtilitiesTest.java
- src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java
- src/test/java/it/gov/pagopa/common/web/exception/ValidationExceptionHandlerTest.java
- src/test/java/it/gov/pagopa/message/connector/citizen/CitizenConnectorImplTest.java
- src/test/java/it/gov/pagopa/message/event/producer/MessageProducerTest.java
- src/test/java/it/gov/pagopa/message/service/MessageCoreServiceTest.java
- src/test/java/it/gov/pagopa/message/service/MessageProducerServiceTest.java
> fix: Test fix

- src/main/java/it/gov/pagopa/common/mongo/MongoConfig.java
- src/test/java/it/gov/pagopa/common/configuration/MongoConfigTest.java
- Added junit for MongoConfig class
> fix: Mongo config test

- src/main/java/it/gov/pagopa/common/configuration/MongoConfig.java
- src/main/java/it/gov/pagopa/common/configuration/MongoHealthConfig.java
- src/main/java/it/gov/pagopa/common/reactive/kafka/consumer/BaseKafkaConsumer.java
- src/main/java/it/gov/pagopa/common/reactive/utils/PerformanceLogger.java
- src/main/java/it/gov/pagopa/common/utils/CommonUtilities.java
- src/main/java/it/gov/pagopa/common/web/dto/ErrorDTO.java
- src/test/java/it/gov/pagopa/common/configuration/MongoConfigTest.java
- src/test/java/it/gov/pagopa/common/reactive/kafka/BaseKafkaConsumerTest.java
- src/test/java/it/gov/pagopa/common/reactive/kafka/TestKafkaConsumer.java
> fix: Kafka consumer test

- src/test/java/it/gov/pagopa/message/utils/TestUtils.java
- src/test/java/it/gov/pagopa/message/utils/faker/MessageDTOFaker.java
- src/test/java/it/gov/pagopa/message/utils/faker/QueueMessageFaker.java
> fix: Sonar maintainability 

- src/main/java/it/gov/pagopa/message/controller/MessageCoreController.java
- src/main/java/it/gov/pagopa/message/controller/MessageCoreControllerImpl.java
- src/main/java/it/gov/pagopa/message/dto/SendResponseDTO.java
- src/test/java/it/gov/pagopa/message/controller/MessageCoreControllerTest.java
Adjustment response of send message
> fix: adjustment of response rest

- src/main/java/it/gov/pagopa/message/controller/MessageCoreController.java
- src/main/java/it/gov/pagopa/message/controller/MessageCoreControllerImpl.java
- src/main/java/it/gov/pagopa/message/dto/SendResponseDTO.java
- src/test/java/it/gov/pagopa/message/controller/MessageCoreControllerTest.java
> fix: promote to UAT

- .devops/code-review-pipelines.yml
- .github/workflows/code-review.yml
- .github/workflows/release.yml
- .github/workflows/snapshot-docker.yml
- .github/workflows/trivy.yml
- Dockerfile
- pom.xml
> chore: depcheck udpate

- Dockerfile
- dep-sha256.json
- pom.xml
> fix: CVE management

- src/main/java/it/gov/pagopa/common/utils/CommonUtilities.java
- src/main/java/it/gov/pagopa/message/service/MessageCoreServiceImpl.java
- src/main/java/it/gov/pagopa/message/service/MessageProducerService.java
- src/main/java/it/gov/pagopa/message/service/MessageProducerServiceImpl.java
- src/test/java/it/gov/pagopa/message/service/MessageCoreServiceTest.java
- src/test/java/it/gov/pagopa/message/service/MessageProducerServiceTest.java
- src/test/java/it/gov/pagopa/message/utils/TestUtils.java
> fix: log injection
